import type { BookingStatus } from "./booking";
import type { ListingStatus, ListingVertical } from "./listing";

// ---------------------------------------------------------------------------
// AdminStats — platform-wide dashboard metrics for the admin panel
// ---------------------------------------------------------------------------
export interface AdminStats {
  totalUsers: number;
  totalHosts: number;
  totalGuests: number;
  totalListings: number;
  totalBookings: number;
  /** Gross revenue collected from guests in Ngwee (integer). Never float. */
  totalRevenueNgwee: number;
  /** Platform's share of revenue in Ngwee (integer). Never float. */
  platformFeeNgwee: number;
  /** Count of host payouts awaiting disbursement */
  pendingPayouts: number;
  activeListings: number;
  /** Count of hosts awaiting KYC verification */
  pendingKYC: number;
}

// ---------------------------------------------------------------------------
// AuditLogEntry — immutable record of every admin action for compliance
// ---------------------------------------------------------------------------
export type AuditTargetType = "user" | "listing" | "booking" | "payout" | "package";

export interface AuditLogEntry {
  id: string;
  adminId: string;
  adminName: string;
  /** Human-readable action label e.g. 'APPROVED_KYC', 'SUSPENDED_LISTING' */
  action: string;
  targetType: AuditTargetType;
  targetId: string;
  /** Optional extra context e.g. rejection reason or changed field values */
  detail: string;
  /** ISO 8601 datetime */
  timestamp: string;
}

// ---------------------------------------------------------------------------
// PayoutQueueItem — a pending or processed payout to a host
// ---------------------------------------------------------------------------
export type PayoutStatus = "pending" | "processing" | "paid";

export interface PayoutQueueItem {
  id: string;
  hostId: string;
  hostName: string;
  /** Amount to disburse in Ngwee (integer). Never float. */
  amountNgwee: number;
  /** ISO 8601 date — start of the payout period */
  periodStart: string;
  /** ISO 8601 date — end of the payout period */
  periodEnd: string;
  status: PayoutStatus;
  /** ISO 8601 datetime when the host requested the payout */
  requestedAt: string;
}

// ---------------------------------------------------------------------------
// AdminBookingRow — enriched booking record for the admin bookings table
// ---------------------------------------------------------------------------
export interface AdminBookingRow {
  id: string;
  bookingRef: string;
  listingId: string;
  listingVertical: ListingVertical;
  guestId: string;
  hostId: string;
  checkIn: string;
  checkOut: string;
  guests: number;
  /** Total charge in Ngwee (integer). Never float. */
  totalNgwee: number;
  /** Platform fee portion in Ngwee (integer). Never float. */
  serviceFeeNgwee: number;
  status: BookingStatus;
  createdAt: string;
  // Denormalised display fields
  guestName: string;
  hostName: string;
  listingTitle: string;
  vertical: ListingVertical;
}

// ---------------------------------------------------------------------------
// AdminListingRow — enriched listing record for the admin listings table
// ---------------------------------------------------------------------------
export interface AdminListingRow {
  id: string;
  title: string;
  slug: string;
  hostId: string;
  hostName: string;
  vertical: ListingVertical;
  status: ListingStatus;
  /** Number of completed bookings for this listing */
  bookingCount: number;
  /** Total gross revenue generated by this listing in Ngwee (integer). */
  revenueNgwee: number;
  rating: number;
  totalReviews: number;
  createdAt: string;
  updatedAt: string;
}
