/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GemsRouteImport } from './routes/gems'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BusBookingRouteImport } from './routes/bus-booking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccommodationsIndexRouteImport } from './routes/accommodations.index'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileHostRouteImport } from './routes/profile.host'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AccommodationsIdRouteImport } from './routes/accommodations.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsRoute = GemsRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BusBookingRoute = BusBookingRouteImport.update({
  id: '/bus-booking',
  path: '/bus-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccommodationsIndexRoute = AccommodationsIndexRouteImport.update({
  id: '/accommodations/',
  path: '/accommodations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileHostRoute = ProfileHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => ProfileRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AccommodationsIdRoute = AccommodationsIdRouteImport.update({
  id: '/accommodations/$id',
  path: '/accommodations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bus-booking': typeof BusBookingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gems': typeof GemsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accommodations/$id': typeof AccommodationsIdRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/profile/host': typeof ProfileHostRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/accommodations/': typeof AccommodationsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus-booking': typeof BusBookingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gems': typeof GemsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accommodations/$id': typeof AccommodationsIdRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/profile/host': typeof ProfileHostRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/accommodations': typeof AccommodationsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bus-booking': typeof BusBookingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gems': typeof GemsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accommodations/$id': typeof AccommodationsIdRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/profile/host': typeof ProfileHostRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/accommodations/': typeof AccommodationsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bus-booking'
    | '/forgot-password'
    | '/gems'
    | '/help'
    | '/login'
    | '/packages'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/accommodations/$id'
    | '/admin/bookings'
    | '/admin/commissions'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/profile/host'
    | '/profile/settings'
    | '/accommodations/'
    | '/admin/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus-booking'
    | '/forgot-password'
    | '/gems'
    | '/help'
    | '/login'
    | '/packages'
    | '/register'
    | '/reset-password'
    | '/accommodations/$id'
    | '/admin/bookings'
    | '/admin/commissions'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/profile/host'
    | '/profile/settings'
    | '/accommodations'
    | '/admin'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bus-booking'
    | '/forgot-password'
    | '/gems'
    | '/help'
    | '/login'
    | '/packages'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/accommodations/$id'
    | '/admin/bookings'
    | '/admin/commissions'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/profile/host'
    | '/profile/settings'
    | '/accommodations/'
    | '/admin/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BusBookingRoute: typeof BusBookingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GemsRoute: typeof GemsRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AccommodationsIdRoute: typeof AccommodationsIdRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  AccommodationsIndexRoute: typeof AccommodationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems': {
      id: '/gems'
      path: '/gems'
      fullPath: '/gems'
      preLoaderRoute: typeof GemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus-booking': {
      id: '/bus-booking'
      path: '/bus-booking'
      fullPath: '/bus-booking'
      preLoaderRoute: typeof BusBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accommodations/': {
      id: '/accommodations/'
      path: '/accommodations'
      fullPath: '/accommodations/'
      preLoaderRoute: typeof AccommodationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/host': {
      id: '/profile/host'
      path: '/host'
      fullPath: '/profile/host'
      preLoaderRoute: typeof ProfileHostRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accommodations/$id': {
      id: '/accommodations/$id'
      path: '/accommodations/$id'
      fullPath: '/accommodations/$id'
      preLoaderRoute: typeof AccommodationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfileRouteChildren {
  ProfileHostRoute: typeof ProfileHostRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileHostRoute: ProfileHostRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BusBookingRoute: BusBookingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GemsRoute: GemsRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AccommodationsIdRoute: AccommodationsIdRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  AccommodationsIndexRoute: AccommodationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
